# Generated by Django 5.0.1 on 2024-01-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='agreement',
            field=models.CharField(choices=[('strongly agree', 'Kesinlikle katılıyorum'), ('agree', 'Katılıyorum'), ('partially agree', 'Kısmen katılıyorum'), ('neutral', 'Nötr'), ('partially disagree', 'kısmen katılmıyorum'), ('disagree', 'katılmıyorum'), ('strongly disagree', 'Kesinlikle katılmıyorum')], max_length=20, verbose_name='agreement'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=60, verbose_name='Soru'),
        ),
    ]
