# Generated by Django 5.0.1 on 2024-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_correlation_delete_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correlation',
            field=models.IntegerField(choices=[(1, '1 - Strongly Agree'), (2, '2 - Agree'), (3, '3 - Slightly Agree'), (4, '4 - Neutral'), (5, '5 - Slightly Disagree'), (6, '6 - Disagree'), (7, '7 - Strongly Disagree')], default=4, verbose_name='Correlation'),
        ),
    ]
