# Generated by Django 5.0.1 on 2024-01-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_question_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correlation',
            field=models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Slightly Agree'), (4, 'Neutral'), (5, 'Slightly Disagree'), (6, 'Disagree'), (7, 'Strongly Disagree'), (8, 'none')], default=8, verbose_name='Korelasyon'),
        ),
    ]
