# Generated by Django 5.0.1 on 2024-01-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_question_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correlation',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Strongly Agree'), (2, 'Agree'), (3, 'Slightly Agree'), (4, 'Slightly Disagree'), (5, 'Disagree'), (6, 'Strongly Disagree'), (7, 'none')], default=7, verbose_name='Korelasyon'),
        ),
    ]
