# Generated by Django 5.0.1 on 2024-01-10 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_question_correlation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correlation',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(choices=[(0, 'Neutral'), (1, 'Strongly Agree'), (2, 'Agree'), (3, 'Disagree'), (4, 'Strongly Disagree'), (5, 'none')], default=5, max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
    ]
