# Generated by Django 5.0.1 on 2024-01-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_choice_question_question_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(0, 'Strongly Agree'), (1, 'Agree'), (2, 'Neutral'), (3, 'Disagree'), (4, 'Strongly Disagree')], default='Neutral', max_length=50, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='question',
            name='overall_agree_answers',
            field=models.IntegerField(default=0, verbose_name='Bu soruya katılanların sayısı'),
        ),
        migrations.AddField(
            model_name='question',
            name='overall_disagree_answers',
            field=models.IntegerField(default=0, verbose_name='Bu soruya katılmayanların sayısı'),
        ),
        migrations.AddField(
            model_name='question',
            name='overall_neutral_answers',
            field=models.IntegerField(default=0, verbose_name='Bu soru için nötr olanların sayısı'),
        ),
        migrations.AddField(
            model_name='question',
            name='overall_strongly_agree_answers',
            field=models.IntegerField(default=0, verbose_name='Bu soruya kesinlikle katılanların sayısı'),
        ),
        migrations.AddField(
            model_name='question',
            name='overall_strongly_disagree_answers',
            field=models.IntegerField(default=0, verbose_name='Bu soruya kesinlikle katılmayanların sayısı'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='your question', max_length=80, verbose_name='Soru'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
