# Generated by Django 5.0.1 on 2024-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_question_choice_remove_question_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(0, 'Kesinlikle katılıyorum'), (1, 'Katılıyorum'), (2, 'Nötr'), (3, 'Katılmıyorum'), (4, 'Kesinlikle katılmıyorum'), (5, 'Henüz cevaplanmadı')], default=5, max_length=50, verbose_name='Cevap'),
        ),
    ]
