# Generated by Django 5.0.1 on 2024-01-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('0', 'Kesinlikle katılıyorum'), ('1', 'Katılıyorum'), ('2', 'Nötr'), ('3', 'Katılmıyorum'), ('4', 'Kesinlikle katılmıyorum'), ('5', 'Henüz cevaplanmadı')], default='5', max_length=50, verbose_name='Cevap'),
        ),
    ]
