# Generated by Django 5.0.1 on 2024-01-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
