# Generated by Django 5.0.1 on 2024-01-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='your question', max_length=125, verbose_name='Soru'),
        ),
    ]
